<!DOCTYPE html><html lang="en"><head><!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-W5DK57Q');</script> 
  <!-- End Google Tag Manager --><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if IE]><link rel="icon" href="/favicon.ico" /><![endif]--><link href="/css/client-chunk-login.807ce826.css" rel="prefetch"><link href="/css/client-chunk-product-details.e6a83c7f.css" rel="prefetch"><title>Covid-19 Tracker</title><link href="/css/client-chunk-products.30a9b90f.css" rel="prefetch"><link href="/js/chunk-firestore.11451822.js" rel="prefetch"><link href="/js/client-chunk-login.3492b2d8.js" rel="prefetch"><link href="/js/client-chunk-product-details.aeda4b33.js" rel="prefetch"><link href="/js/client-chunk-products.9796385b.js" rel="prefetch"><link href="/css/app.bdf5a745.css" rel="preload" as="style"><link href="/css/chunk-vendors.b1764a9c.css" rel="preload" as="style"><link href="/js/app.355d2cb8.js" rel="preload" as="script"><link href="/js/chunk-vendors.d7f1feee.js" rel="preload" as="script"><link href="/css/chunk-vendors.b1764a9c.css" rel="stylesheet"><link href="/css/app.bdf5a745.css" rel="stylesheet"><link rel="icon" type="image/png" sizes="32x32" href="/img/favicon.ico"><link rel="icon" type="image/png" sizes="16x16" href="/img/favicon.ico"><link rel="manifest" href="/manifest.json"><meta name="theme-color" content="#FFFFFF"><meta name="apple-mobile-web-app-capable" content="no"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="apple-mobile-web-app-title" content="covid-tracker"><link rel="apple-touch-icon" href="/img/icons/apple-touch-icon-152x152.png"><link rel="mask-icon" href="/img/icons/safari-pinned-tab.svg" color="#FFFFFF"><meta name="msapplication-TileImage" content="/img/favicon.ico"><meta name="msapplication-TileColor" content="#000000"><link rel="icon" href="/img/favicon.ico"><link rel="icon" href="/img/favicon.ico" sizes="192x192"><meta name="mobile-web-app-capable" content="yes"><meta name="x5-page-mode" content="app"><meta name="browsermode" content="application"></head><body><!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W5DK57Q"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> 
<!-- End Google Tag Manager (noscript) --><noscript><strong>We're sorry but Covid-Tracker doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><main role="main"><div id="app"><header data-v-5d9332dc="" class="navbar"><a data-v-5d9332dc="" href="#/home" class="router-link-exact-active router-link-active"><img data-v-5d9332dc="" alt="logo-bento" src="/img/covidIm.911caab2.png" class="logo"><span data-v-5d9332dc="" class="site-name title-desktop">Covid-Tracker</span><span data-v-5d9332dc="" class="site-name title-mobile">CovidTracker</span></a><div data-v-5d9332dc="" class="links"><nav data-v-5d9332dc="" class="nav-links"><div data-v-5d9332dc="" class="nav-item"><a data-v-5d9332dc="" href="#/india" class="">India</a></div><div data-v-5d9332dc="" class="nav-item"><a data-v-5d9332dc="" href="#/world" class="">Global</a></div><!----></nav><!----></div></header><div class="main-wrapper"><!----></div><!----><!----></div></main><script src="/js/chunk-vendors.d7f1feee.js"></script><script src="/js/app.355d2cb8.js"></script></body></html>
